[pytest]
testpaths =
    ui_tests/tests

addopts =
    --alluredir=automation-test-results/allure-results
    -v
    --tb=short
    --reruns=2
    --reruns-delay=1

log_cli            = true
log_cli_level      = INFO
log_format         = %(asctime)s [%(levelname)-8s] %(name)s: %(message)s
log_date_format    = %Y-%m-%d %H:%M:%S

markers =
    ui:         UI / browser-level tests
    smoke:      Critical-path smoke suite
    regression: Full regression suite
